nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: BileMo phones
            description: API for BileMo's client
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    name: authorization
                    in: header
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/(doc|doc.json)$) # Accepts routes under /api except /api/doc
